#!/bin/bash

wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.bz2

java -Xmx450m -jar /opt/splitter-r321/splitter.jar --mapid=63245000 berlin-latest.osm.bz2

java -Xmx450m -jar /opt/mkgmap-r3241/mkgmap.jar --description="OpenStreetMap of Berlin (GER)" --latin1 --net --gmapsupp --route --remove-shreas --index *.osm.pbf
